#index:
    #path: /hello
    #controller: App\Controller\HelloController::hello

#toto:
    #path: /listing
    #controller: App\Controller\HelloController::listing

#request:
    #path: /page
    #controller: App\Controller\HelloController::page
